spring:
  application:
    name: SplitIo-POC
  server:
    port: 8081
  logging:
    level:
      com:
        example:
          connect:
            splitio: DEBUG
  custom:
    logging:
      package: com.example.connect.splitio

split:
  apiKey: WILL SHARE IT PRIVATELY
