spring:
  application:
    name: SplitIo-POC
  server:
    port: 8081
  logging:
    level:
      com:
        digicert:
          drz:
            splitio: DEBUG
  custom:
    logging:
      package: com.digicert.drz.splitio

split:
  apiKey: WILL SHARE IT PRIVATELY
